# Generated by Django 2.2.6 on 2019-11-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191108_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employeeOf',
            new_name='employer',
        ),
    ]
