# Generated by Django 2.2.6 on 2019-11-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191107_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birthdate',
        ),
    ]
