# Generated by Django 2.2.6 on 2019-11-08 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('surname', models.CharField(max_length=30, null=True)),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='date when added')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('clientOf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('quantity_available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.FloatField(blank=True)),
                ('ol', models.FloatField(blank=True)),
                ('op_astigm', models.FloatField(blank=True)),
                ('ol_astigm', models.FloatField(blank=True)),
                ('op_axis', models.FloatField(blank=True)),
                ('ol_axis', models.FloatField(blank=True)),
                ('pd', models.FloatField(blank=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='order date')),
                ('comment', models.TextField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('n', 'new'), ('w', 'waiting for parts'), ('l', 'lab'), ('r', 'ready'), ('p', 'picked up')], default='n', max_length=1)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.Client')),
                ('parameters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.Parameters')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of appointment')),
                ('comment', models.TextField(blank=True, max_length=400, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.Client')),
                ('parameters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.Parameters')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
