# Generated by Django 2.2.4 on 2019-09-03 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.FloatField()),
                ('ol', models.FloatField()),
                ('op_astigm', models.FloatField()),
                ('ol_astigm', models.FloatField()),
                ('op_axis', models.FloatField()),
                ('ol_axis', models.FloatField()),
                ('pd', models.FloatField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of appointment')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.Client')),
                ('parameters', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.Parameters')),
            ],
        ),
    ]
