# Generated by Django 2.2.4 on 2019-09-03 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_appointment_parameters_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='parameters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.Parameters'),
        ),
    ]
