# Generated by Django 2.2.4 on 2019-09-03 15:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20190903_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='comment',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='order date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='parameters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.Parameters'),
        ),
        migrations.AddField(
            model_name='order',
            name='parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('n', 'new'), ('w', 'waiting for parts'), ('l', 'lab'), ('r', 'ready'), ('p', 'picked up')], default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date when added'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='ol',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='ol_astigm',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='ol_axis',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='op',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='op_astigm',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='op_axis',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='pd',
            field=models.FloatField(blank=True),
        ),
    ]
