# Generated by Django 2.2.4 on 2019-09-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20190903_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantity_available',
        ),
        migrations.RemoveField(
            model_name='order',
            name='parts',
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
