# Generated by Django 2.2.6 on 2019-10-30 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_client_clientof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
