# Generated by Django 2.2.6 on 2019-11-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_auto_20191030_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Company'),
        ),
    ]
